routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use \App\Http\Requests\ContactRequest;
use \App\Contact;
use \App\Beer;
use \App\Event;
use \App\Article;
use \App\Slide;
use \App\Callout;


Auth::routes();

Route::get('/', function () {
    $slides = Slide::where('active', true)
            ->orderBy('weight')
            ->limit(5)
            ->get();
    $callouts = Callout::where('active', true)
              ->orderBy('weight', 'id')
              ->limit(3)
              ->get();
    $beers = Beer::limit(3)->get();
    $events = Event::where('date', '>', DB::raw('current_date - 1'))
            ->orderBy('date', 'asc')
            ->limit(4)
            ->get();
    return view('welcome', compact('slides', 'callouts', 'beers', 'events'));
});

Route::get('/beers', function() {
    $beers = Beer::orderBy('title')->get();
    return view('beers', compact('beers'));
});

Route::get('/taproom', function() {
    return view('taproom');
});

Route::get('/events', function() {
    $events = Event::where('date', '>', DB::raw('current_date - 1'))
            ->orderBy('date', 'asc')
            ->simplePaginate(9);
    return view('events', compact('events'));
});

Route::get('/events/{slug}', function($slug) {
    $event = Event::where('slug', $slug)->first();
    if (empty($event)) {
        return redirect('/events');
    }
    return view('event', compact('event'));
});

Route::get('/news', function() {
    $articles = Article::where('date', '<=', DB::raw('current_date'))
        ->orderBy('date', 'desc')
        ->simplePaginate(4);

    $years = DB::table('articles')
           ->select(DB::raw('extract(year from date)'))
           ->distinct()
           ->get();

    return view('news', compact('articles', 'years'));
});

Route::get('/news/{slug}', function($slug) {
    $article = Article::where('slug', $slug)->first();
    $next = Article::where('date', '>', $article->date)->first();
    $prev = Article::where('date', '<', $article->date)->first();
    $years = DB::table('articles')
           ->select(DB::raw('extract(year from date)'))
           ->distinct()
           ->get();

    if (empty($article)) {
        return redirect('news');
    }

    return view('article', compact('slug', 'article', 'next', 'prev', 'years'));
});

Route::get('/news/archives/{year}', function($year) {
    $articles = Article::where(DB::raw('extract(year from date)'), '=', $year)
              ->orderBy('date', 'desc')
              ->simplePaginate(4);

    $years = DB::table('articles')
           ->select(DB::raw('extract(year from date)'))
           ->distinct()
           ->get();

    return view('news-archive', compact('articles', 'years', 'year'));
});

Route::get('/contact', function() {
    return view('contact');
});

Route::get('/contact/thank-you', function() {
	return view('contact-thank-you');
});

Route::post('/contact', function(ContactRequest $request) {
    // If any of this code happens, it means ContactRequest
    // validated correctly

    // Store the request in the database
	Contact::create(request(['name', 'phone', 'email', 'message']));

    // Redirect to thank-you page
	return redirect('/contact/thank-you');
});


// ----------------------------------------------------------------
// Admin Routes
// ----------------------------------------------------------------

Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('', 'Controller@index');
    Route::resource('slides', 'SlidesController');
    Route::resource('callouts', 'CalloutsController');
    Route::resource('beers', 'BeersController');
    Route::resource('beer-types', 'BeerTypesController');
    Route::resource('events', 'EventsController');
    Route::resource('articles', 'NewsController');

    // Contact Requests
    Route::get('contacts', 'ContactsController@index');
    Route::get('contacts/{contact}', 'ContactsController@show');
    Route::delete('contacts/{contact}', 'ContactsController@destroy');

	// Weird URL due to conflict with BeerController@update
	Route::post('/upload/beers', 'BeersController@upload');
	// Route::post('/upload/beers', function() {
	// 	return response()->json(['testing' => '123']);
	// });
});


// ----------------------------------------------------------------
// JSOn API Routes
// ----------------------------------------------------------------

Route::group(['prefix' => 'api', 'namespace' => 'API'], function() {
	Route::get('beers', 'BeersController@index');
});

app/Slide.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slide extends Model
{
    //
    protected $fillable = [
        'title',
        'active',
        'link',
    ];
}

app/Http/Controllers/Admin/SlidesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Slide;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SlidesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $slides = Slide::all();
        return view('admin.slides.index', compact('slides'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $slide = new Slide;
        return view('admin.slides.create', compact('slide'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $slide = new Slide;
        $slide->fill(request([
            'title',
            'link',
            'active',
        ]));

        $slide->weight = 1;
        $slide->image = request()->file('image')->store('public');

        if ($slide->save()) {
            return redirect(route('slides.index'));
        } else {
            return view('admin.slides.create', compact('slide'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function show(Slide $slide)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function edit(Slide $slide)
    {
        return view('admin.slides.edit', compact('slide'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Slide $slide)
    {
        $slide->fill(request([
            'title',
            'link',
            'active',
        ]));

        $slide->weight = 1;
        if (!empty(request()->file('image')))
        {
            $slide->image = request()->file('image')->store('public');
        }

        if ($slide->save()) {
            return redirect(route('slides.index'));
        } else {
            return view('admin.slides.edit', compact('slide'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function destroy(Slide $slide)
    {
        //
    }
}

resources/views/admin/slides/_fields.blade.php
{{ csrf_field() }}


<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label>
                <input name="active" type="checkbox" value="1" {{ $slide->active ? 'checked=checked':'' }}/>
                Active
            </label>
        </div>

        <div class="form-group">
            <label for="image">Image (suggested minimum: 1600px &times; 400px)</label>
            <input type="file" name="image" id="image" />
            @if(!empty($slide->image))
                <img class="img-responsive" alt="" src="{{ asset(Storage::url($slide->image)) }}"/>
            @endif
        </div>
    </div>
</div>


<div class="row">
    <div class="form-group col-sm-6">
        <label for="title">Overlay text</label>
        <input id="title" name="title" type="text" value="{{ $slide->title }}" class="form-control"/>
    </div>

    <div class="form-group col-sm-6">
        <label for="link">Link <span class="required">*</span></label>
        <input id="link" class="form-control" name="link" type="text" value="{{ $slide->link }}"/>
    </div>
</div>

resources/views/admin/slides/create.blade.php
@extends('layouts.admin')

@section('title', 'New Slide')

@section('breadcrumb')
    <li><a href="{{ route('slides.index') }}">Slides</a></li>
    <li>New Slide</li>
@endsection

@section('content')
<div class="container">
    <form method="POST" action="{{ route('slides.store') }}" enctype="multipart/form-data">
        <div class="row">

            <div class="col-sm-12">
                @include('admin.slides._fields')
            </div>

            <div class="col-sm-12">
                <button class="btn btn-default">Create</button>
            </div>

        </div>

    </form>
</div>
@endsection

resources/views/admin/slides/edit.blade.php
@extends('layouts.admin')

@section('title', $slide->title)

@section('breadcrumb')
    <li><a href="{{ route('slides.index') }}">Slides</a></li>
    <li>{{ $slide->title }}</li>
@endsection

@section('content')
<div class="container">
    <form method="POST" action="{{ route('slides.update', $slide) }}" enctype="multipart/form-data">
        {{ method_field('PUT') }}

        <div class="row">

            <div class="col-sm-12">
                @include('admin.slides._fields')
            </div>

            <div class="col-sm-12">
                <button class="btn btn-default">Update</button>
            </div>

        </div>

    </form>
</div>
@endsection

resources/views/admin/slides/index.blade.php
@extends('layouts.admin')

@section('title', 'Homepage Slides')

@section('breadcrumb')
    <li>Slides</li>
@endsection

@section('content')
    <div class="container">

        <a class="btn btn-success pull-right" href="{{ route('slides.create') }}"><i class="glyphicon glyphicon-plus"></i> Add Slide</a>

        <table class="table table-hover table-striped">
            <colgroup>
                <col class="title"/>
                <col class="manage"/>
            </colgroup>

            <thead>
                <th>Title</th>
                <th width="15%">Manage</th>
            </thead>

            <tbody>
                @foreach ($slides as $row)
                    <tr>
                        <td>{{ $row->title }}</td>
                        <td>
                            <a class="btn btn-default btn-xs" href="{{ route('slides.edit', ['type' => $row]) }}">Edit</a>

                            <form method="POST" action="{{ route('slides.destroy', ['type' => $row]) }}" class="confirm inline-block">
                                {{ csrf_field() }}
                                {{ method_field('delete') }}
                                <button class="btn btn-xs btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection