routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use \App\Http\Requests\ContactRequest;
use \App\Contact;
use \App\Beer;
use \App\Event;
use \App\Article;
use \App\Slide;
use \App\Callout;


Auth::routes();

Route::get('/', function () {
    $slides = Slide::where('active', true)
            ->orderBy('weight')
            ->limit(5)
            ->get();
    $callouts = Callout::where('active', true)
              ->orderBy('weight', 'id')
              ->limit(3)
              ->get();
    $beers = Beer::limit(3)->get();
    $events = Event::where('date', '>', DB::raw('current_date - 1'))
            ->orderBy('date', 'asc')
            ->limit(4)
            ->get();
    return view('welcome', compact('slides', 'callouts', 'beers', 'events'));
});

Route::get('/beers', function() {
    $beers = Beer::orderBy('title')->get();
    return view('beers', compact('beers'));
});

Route::get('/taproom', function() {
    return view('taproom');
});

Route::get('/events', function() {
    $events = Event::where('date', '>', DB::raw('current_date - 1'))
            ->orderBy('date', 'asc')
            ->simplePaginate(9);
    return view('events', compact('events'));
});

Route::get('/events/{slug}', function($slug) {
    $event = Event::where('slug', $slug)->first();
    if (empty($event)) {
        return redirect('/events');
    }
    return view('event', compact('event'));
});

Route::get('/news', function() {
    $articles = Article::where('date', '<=', DB::raw('current_date'))
        ->orderBy('date', 'desc')
        ->simplePaginate(4);

    $years = DB::table('articles')
           ->select(DB::raw('extract(year from date)'))
           ->distinct()
           ->get();

    return view('news', compact('articles', 'years'));
});

Route::get('/news/{slug}', function($slug) {
    $article = Article::where('slug', $slug)->first();
    $next = Article::where('date', '>', $article->date)->first();
    $prev = Article::where('date', '<', $article->date)->first();
    $years = DB::table('articles')
           ->select(DB::raw('extract(year from date)'))
           ->distinct()
           ->get();

    if (empty($article)) {
        return redirect('news');
    }

    return view('article', compact('slug', 'article', 'next', 'prev', 'years'));
});

Route::get('/news/archives/{year}', function($year) {
    $articles = Article::where(DB::raw('extract(year from date)'), '=', $year)
              ->orderBy('date', 'desc')
              ->simplePaginate(4);

    $years = DB::table('articles')
           ->select(DB::raw('extract(year from date)'))
           ->distinct()
           ->get();

    return view('news-archive', compact('articles', 'years', 'year'));
});

Route::get('/contact', function() {
    return view('contact');
});

Route::get('/contact/thank-you', function() {
	return view('contact-thank-you');
});

Route::post('/contact', function(ContactRequest $request) {
    // If any of this code happens, it means ContactRequest
    // validated correctly

    // Store the request in the database
	Contact::create(request(['name', 'phone', 'email', 'message']));

    // Redirect to thank-you page
	return redirect('/contact/thank-you');
});


// ----------------------------------------------------------------
// Admin Routes
// ----------------------------------------------------------------

Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('', 'Controller@index');
    Route::resource('slides', 'SlidesController');
    Route::resource('callouts', 'CalloutsController');
    Route::resource('beers', 'BeersController');
    Route::resource('beer-types', 'BeerTypesController');
    Route::resource('events', 'EventsController');
    Route::resource('articles', 'NewsController');

    // Contact Requests
    Route::get('contacts', 'ContactsController@index');
    Route::get('contacts/{contact}', 'ContactsController@show');
    Route::delete('contacts/{contact}', 'ContactsController@destroy');

	// Weird URL due to conflict with BeerController@update
	Route::post('/upload/beers', 'BeersController@upload');
	// Route::post('/upload/beers', function() {
	// 	return response()->json(['testing' => '123']);
	// });
});


// ----------------------------------------------------------------
// JSOn API Routes
// ----------------------------------------------------------------

Route::group(['prefix' => 'api', 'namespace' => 'API'], function() {
	Route::get('beers', 'BeersController@index');
});

app/Beer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Beer extends Model
{
	protected $fillable = ['title', 'beer_type', 'abv', 'ibu', 'description', 'og_image', 'image', 'cropdata'];

    // public function type()
    // {
    //     return $this->belongsTo('App\BeerType', 'beer_type_id');
    // }
}

app/BeerType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BeerType extends Model
{
	protected $fillable = ['title'];

    public function beers()
    {
        return $this->hasMany('App\Beer', 'beer_type_id');
    }
}

app/Http/Controllers/API/BeersController.php
<?php
namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

use \App\Beer;
use \App\Http\Controllers\Controller;


class BeersController extends Controller
{
	/**
	 * Return a JSON array of the beers data.
	 *
	 * @return string
	 */
	public function index()
	{
		$beers = Beer::orderBy('title')->get();
		foreach ($beers as &$beer) {
			$beer->realImage = asset(Storage::url($beer->image));
		}
		return $beers->jsonSerialize();
	}
}

app/Http/Controllers/Admin/BeersController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

use \App\Beer;
use \App\BeerType;
use \App\Facades\Cropper;

class BeersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $beers = Beer::orderBy('title')->get();
        return view('admin.beers.index', compact('beers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $beer = new Beer;
        $types = BeerType::orderBy('title')->get();
        return view('admin.beers.create', compact('beer', 'types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      /* $beer = new Beer(request(['title', 'beer_type_id', 'abv', 'ibu', 'description', 'og_image']));*/
        $beer = new Beer(request(['title', 'beer_type', 'abv', 'ibu', 'description', 'og_image']));

        if ($beer->save()) {
            return redirect(route('beers.index'));
        }
        else {
            $types = BeerType::orderBy('title')->get();
            return view('admin.beers.create', compact('beer', 'types'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $beer = Beer::find($id);
        return view('admin.beers.show', compact('beer'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $beer = Beer::find($id);
        $types = BeerType::orderBy('title')->get();
		$beer->cropdata = json_encode(array(
			'x' => 0,
			'y' => 0,
			'width' => 800,
			'height' => 600,
		));
        return view('admin.beers.edit', compact('beer', 'types'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $beer = Beer::find($id);
        $beer->update(request(['title', 'beer_type_id', 'abv', 'ibu', 'description', 'og_image']));

		// Create cropped version of beer image
		$croppedUrl = Cropper::crop($beer->og_image, [
			'x'      => request('crop_x'),
			'y'      => request('crop_y'),
			'width'  => request('crop_w'),
			'height' => request('crop_h'),
		]);

		// Update beer image
		$beer->image = $croppedUrl;

        if ($beer->save()) {
            return redirect(route('beers.index'));
        }
        else {
            $types = BeerType::orderBy('title')->get();
            return view('admin.beers.edit', compact('beer', 'types'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Beer::destroy($id);
        return redirect(route('beers.index'));
    }

	public function upload()
	{
		$path = request()->file('image')->store('public/beers');
		$url = Storage::url($path);

		return response()->json([
			'path' => $path,
			'url' => $url,
		]);
	}
}

resources/views/admin/beers/_fields.blade.php
{{ csrf_field() }}

<input type="hidden" name="og_image" id="og_image" value="{{ $beer->og_image }}" />

<input type="hidden" name="crop_x" id="crop_x" value="" />
<input type="hidden" name="crop_y" id="crop_y" value="" />
<input type="hidden" name="crop_w" id="crop_w" value="" />
<input type="hidden" name="crop_h" id="crop_h" value="" />

<div class="row">
	<div class="form-group col-sm-6">
		<label for="title">Title</label>
		<input class="form-control" id="title" name="title" type="text" value="{{ $beer->title }}"/>
	</div>

	<div class="form-group col-sm-6">
		<label for="beer_type">Type</label>
		<input class="form-control" id="beer_type" name="beer_type" type="text" value="{{ $beer->beer_type }}"/>
		{{-- <label for="beer_type_id">Type</label> --}}
		{{-- <select id="beer_type_id" name="beer_type_id" class="form-control"> --}}
		{{-- <option>select one</option> --}}
		{{-- @foreach ($types as $type) --}}
		{{-- <option value="{{ $type->id }} " {{ $type->id==$beer->beer_type_id?'selected':'' }}>{{ $type->title }}</option> --}}
		{{-- @endforeach --}}
		{{-- </select> --}}
	</div>
</div>

<div class="row">
	<div class="form-group col-sm-6">
		<label for="abv">ABV</label>
		<input class="form-control" id="abv" name="abv" type="number" step="0.1" value="{{ $beer->abv }}"/>
	</div>

	<div class="form-group col-sm-6">
		<label for="abv">IBU</label>
		<input class="form-control" id="ibu" name="ibu" type="number" value="{{ $beer->ibu }}"/>
	</div>
</div>

<div class="form-group">
	<label for="description">Description</label>
	<textarea cols="30" id="description" class="form-control" name="description" rows="5">{{ $beer->description }}</textarea>
</div>

resources/views/admin/beers/create.blade.php
@extends('layouts.admin')

@section('title', 'New Beer')

@section('breadcrumb')
    <li><a href="{{ route('beers.index') }}">Beers</a></li>
    <li>New Beer</li>
@endsection

@section('content')
<div class="container">
	<div class="row">

		<div class="col-sm-8">
			<form method="POST" action="{{ route('beers.store') }}">
				@include('admin.beers._fields')
				<button class="btn btn-default">Create</button>
			</form>
		</div>

		<div class="col-sm-4">
			<form action="/admin/upload/beers" method="POST">
				{{ csrf_field() }}
				<div class="form-group">
					<label for="image">Image (800px &times; 600px)</label>
					<input type="file" name="image" id="image" />
				</div>

				<div class="form-group">
					<img id="img-crop" src="{{ asset('img/800x600.png') }}" alt="croppable" class="img-responsive" />
				</div>
			</form>
		</div>

	</div>
</div>
@endsection

@section('css')
<link rel="stylesheet" href="{{ asset('css/cropping.css') }}" />
@endsection

@section('js')
<script src="{{ asset('js/cropping.js') }}"></script>
@endsection

resources/views/admin/beers/edit.blade.php
@extends('layouts.admin')

@section('title', $beer->title)

@section('breadcrumb')
    <li><a href="{{ route('beers.index') }}">Beers</a></li>
    <li>{{ $beer->title }}</li>
@endsection

@section('content')
<div class="container">
	<div class="row">
		<div class="col-sm-8">
			<form method="POST" action="{{ route('beers.update', ['beer' => $beer]) }}" enctype="multipart/form-data">
				{{ method_field('put') }}
				@include('admin.beers._fields')
				<button class="btn btn-default">Update</button>
			</form>
		</div>

		<form action="/admin/upload/beers" method="POST">
			{{ csrf_field() }}
			<div class="col-sm-4">
				<div class="form-group">
					<label for="image">Image (800px &times; 600px)</label>
					<input type="file" name="image" id="image" />
				</div>

				<div class="form-group">
					<img id="img-crop" src="{{ asset(Storage::url($beer->og_image)) }}" alt="croppable" class="img-responsive" {{ isset($beer->cropdata)&&!empty($beer->cropdata)?'data-crop='.$beer->cropdata:'' }} />
				</div>
			</div>
		</form>

	</div>
</div>
@endsection

@section('css')
<link rel="stylesheet" href="{{ asset('css/cropping.css') }}" />
@endsection

@section('js')
<script src="{{ asset('js/cropping.js') }}"></script>
@endsection

resources/views/admin/beers/index.blade.php
@extends('layouts.admin')

@section('title', 'Beers')

@section('breadcrumb')
    <li>Beers</li>
@endsection

@section('content')
    <div class="container">

        <a class="btn btn-success pull-right" href="{{ route('beers.create') }}"><i class="glyphicon glyphicon-plus"></i> Add Beer</a>

        <table class="table table-hover table-striped">
            <thead>
                <th>Title</th>
                <th>Type</th>
                <th>ABV</th>
                <th>IBU</th>
                <th width="15%">Manage</th>
            </thead>
            <tbody>
                @foreach ($beers as $row)
                    <tr>
                        <td>{{ $row->title }}</td>
                        <td>{{ $row->title }}</td>
                        <td>{{ $row->abv }}</td>
                        <td>{{ $row->ibu }}</td>
                        <td>
                            <a class="btn btn-default btn-xs" href="{{ route('beers.edit', ['type' => $row]) }}">Edit</a>

                            <form method="POST" action="{{ route('beers.destroy', ['type' => $row]) }}" class="confirm inline-block">
                                {{ csrf_field() }}
                                {{ method_field('delete') }}
                                <button class="btn btn-xs btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection