routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use \App\Http\Requests\ContactRequest;
use \App\Contact;
use \App\Beer;
use \App\Event;
use \App\Article;
use \App\Slide;
use \App\Callout;


Auth::routes();

Route::get('/', function () {
    $slides = Slide::where('active', true)
            ->orderBy('weight')
            ->limit(5)
            ->get();
    $callouts = Callout::where('active', true)
              ->orderBy('weight', 'id')
              ->limit(3)
              ->get();
    $beers = Beer::limit(3)->get();
    $events = Event::where('date', '>', DB::raw('current_date - 1'))
            ->orderBy('date', 'asc')
            ->limit(4)
            ->get();
    return view('welcome', compact('slides', 'callouts', 'beers', 'events'));
});

Route::get('/beers', function() {
    $beers = Beer::orderBy('title')->get();
    return view('beers', compact('beers'));
});

Route::get('/taproom', function() {
    return view('taproom');
});

Route::get('/events', function() {
    $events = Event::where('date', '>', DB::raw('current_date - 1'))
            ->orderBy('date', 'asc')
            ->simplePaginate(9);
    return view('events', compact('events'));
});

Route::get('/events/{slug}', function($slug) {
    $event = Event::where('slug', $slug)->first();
    if (empty($event)) {
        return redirect('/events');
    }
    return view('event', compact('event'));
});

Route::get('/news', function() {
    $articles = Article::where('date', '<=', DB::raw('current_date'))
        ->orderBy('date', 'desc')
        ->simplePaginate(4);

    $years = DB::table('articles')
           ->select(DB::raw('extract(year from date)'))
           ->distinct()
           ->get();

    return view('news', compact('articles', 'years'));
});

Route::get('/news/{slug}', function($slug) {
    $article = Article::where('slug', $slug)->first();
    $next = Article::where('date', '>', $article->date)->first();
    $prev = Article::where('date', '<', $article->date)->first();
    $years = DB::table('articles')
           ->select(DB::raw('extract(year from date)'))
           ->distinct()
           ->get();

    if (empty($article)) {
        return redirect('news');
    }

    return view('article', compact('slug', 'article', 'next', 'prev', 'years'));
});

Route::get('/news/archives/{year}', function($year) {
    $articles = Article::where(DB::raw('extract(year from date)'), '=', $year)
              ->orderBy('date', 'desc')
              ->simplePaginate(4);

    $years = DB::table('articles')
           ->select(DB::raw('extract(year from date)'))
           ->distinct()
           ->get();

    return view('news-archive', compact('articles', 'years', 'year'));
});

Route::get('/contact', function() {
    return view('contact');
});

Route::get('/contact/thank-you', function() {
	return view('contact-thank-you');
});

Route::post('/contact', function(ContactRequest $request) {
    // If any of this code happens, it means ContactRequest
    // validated correctly

    // Store the request in the database
	Contact::create(request(['name', 'phone', 'email', 'message']));

    // Redirect to thank-you page
	return redirect('/contact/thank-you');
});


// ----------------------------------------------------------------
// Admin Routes
// ----------------------------------------------------------------

Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('', 'Controller@index');
    Route::resource('slides', 'SlidesController');
    Route::resource('callouts', 'CalloutsController');
    Route::resource('beers', 'BeersController');
    Route::resource('beer-types', 'BeerTypesController');
    Route::resource('events', 'EventsController');
    Route::resource('articles', 'NewsController');

    // Contact Requests
    Route::get('contacts', 'ContactsController@index');
    Route::get('contacts/{contact}', 'ContactsController@show');
    Route::delete('contacts/{contact}', 'ContactsController@destroy');

	// Weird URL due to conflict with BeerController@update
	Route::post('/upload/beers', 'BeersController@upload');
	// Route::post('/upload/beers', function() {
	// 	return response()->json(['testing' => '123']);
	// });
});


// ----------------------------------------------------------------
// JSOn API Routes
// ----------------------------------------------------------------

Route::group(['prefix' => 'api', 'namespace' => 'API'], function() {
	Route::get('beers', 'BeersController@index');
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
        'title',
        'date',
        'start_time',
        'end_time',
        'price',
        'body',
        'photo',
        'venue',
        'address',
    ];

    protected $dates = [
        'date',
        'updated_at',
        'created_at',
    ];
}

resources/views/admin/articles/_fields.blade.php
{{ csrf_field() }}

<div class="row">
    <div class="form-group col-sm-8">
        <label for="title">Title</label>
        <input id="title" name="title" type="text" value="{{ $article->title }}" class="form-control"/>
    </div>

    <div class="form-group col-sm-4">
        <label for="date">Date</label>
        <input id="date" name="date" type="date" value="{{ $article->date?$article->date->format('Y-m-d'):'' }}" class="datepicker form-control"/>
    </div>
</div>

<div class="row">
    <div class="form-group col-sm-12">
        <label for="body">Article Body</label>
        <input id="body" name="body" type="hidden" value="{{ $article->body }}"/>
        <div id="toolbar"></div>
        <div id="quill-editor" data-field="body">{!! $article->body !!}</div>
    </div>
</div>

resources/views/admin/articles/create.blade.php
@extends('layouts.admin')

@section('title', 'New Article')

@section('breadcrumb')
    <li><a href="{{ route('articles.index') }}">Articles</a></li>
    <li>Articles</li>
@endsection

@section('content')
<div class="container">
    <form method="POST" action="{{ route('articles.store') }}" enctype="multipart/form-data">
        <div class="row">

            <div class="col-sm-8">
                @include('admin.articles._fields')
                <button class="btn btn-default">Create</button>
            </div>

            <div class="col-sm-4">
                <div class="form-group">
                    <label for="image">Image (900px &times; 500px)</label>
                    <input type="file" name="photo" id="photo" />
                </div>
            </div>

        </div>

    </form>
</div>
@endsection

resources/views/admin/articles/edit.blade.php
@extends('layouts.admin')

@section('title', $article->title)

@section('breadcrumb')
    <li><a href="{{ route('articles.index') }}">Articles</a></li>
    <li>{{ $article->title }}</li>
@endsection

@section('content')
<div class="container">
    <form method="POST" action="{{ route('articles.update', $article) }}" enctype="multipart/form-data">
        <div class="row">
            {{ method_field('put') }}

            <div class="col-sm-8">
                @include('admin.articles._fields')
                <button class="btn btn-default">Update</button>
            </div>

            <div class="col-sm-4">
                <div class="form-group">
                    <label for="image">Image (900px &times; 500px)</label>
                    <input type="file" name="photo" id="photo" />
                </div>

                @if(!empty($article->photo))
                    <div class="form-group">
                        <img id="img-crop" src="{{ asset(Storage::url($article->photo)) }}" alt="croppable" class="img-responsive" />
				            </div>
                @endif
            </div>

        </div>

    </form>
</div>
@endsection

resources/views/admin/articles/index.blade.php
@extends('layouts.admin')

@section('title', 'News Articles')

@section('breadcrumb')
    <li>News Articles</li>
@endsection

@section('content')
    <div class="container">

        <a class="btn btn-success pull-right" href="{{ route('articles.create') }}"><i class="glyphicon glyphicon-plus"></i> Add Article</a>

        <table class="table table-hover table-striped">
            <thead>
                <th width="15%">Date</th>
                <th>Title</th>
                <th width="15%">Manage</th>
            </thead>
            <tbody>
                @foreach ($articles as $row)
                    <tr>
                        <td>{{ $row->date->format('M j, Y') }}</td>
                        <td>{{ $row->title }}</td>
                        <td>
                            <a class="btn btn-default btn-xs" href="{{ route('articles.edit', ['type' => $row]) }}">Edit</a>

                            <form method="POST" action="{{ route('articles.destroy', ['type' => $row]) }}" class="confirm inline-block">
                                {{ csrf_field() }}
                                {{ method_field('delete') }}
                                <button class="btn btn-xs btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection